#!/usr/bin/with-contenv bash
#shellcheck shell=bash disable=SC2016

# CHECK PATH
# FIX SYNTAX TO SPECIFY CONF FILES!
gpsd /dev/ttyACM0 \
--badtime \
--debug 1 \
--foreground \
--listenany \
--nowait \
--port 2947 \
--readonly \
--sockfile /var/run/gpsd.sock 2>&1 | \
    stdbuf -oL awk '{print "[" strftime("%Y/%m/%d %H:%M:%S", systime()) "][gpsd] " $0}'

    