#!/usr/bin/with-contenv bash
#shellcheck shell=bash disable=SC2016
###############################################################################
# Documentation at https://gpsd.gitlab.io/gpsd/gpsd.html
###############################################################################
EXEC_CMD="/usr/sbin/gpsd"
GPS_DEVICE="${GPS_DEVICE}"

CMDLINE=()
CMDLINE+=(--badtime)
CMDLINE+=(--debug 2)
CMDLINE+=(--foreground)
CMDLINE+=(--listenany)
CMDLINE+=(--nowait)
#CMDLINE+=(--port 2947)
#CMDLINE+=(--readonly)
CMDLINE+=(--sockfile /var/run/gpsd.sock)

gpsd_cmd="$(echo ${EXEC_CMD} ${GPS_DEVICE} ${CMDLINE[@]} | xargs)"

echo "[$(date)][gpsd] Starting: ${gpsd_cmd}"

#${gpsd_cmd} -- 2>&1 | \
#    stdbuf -oL awk '{print "[" strftime("%Y/%m/%d %H:%M:%S", systime()) "][gpsd] " $0}'

${gpsd_cmd} -- 2>&1 | \
stdbuf -oL grep -v 'gpsd:WARN: cycle-start detector failed.' | \
stdbuf -oL awk '{print "[" strftime("%Y/%m/%d %H:%M:%S", systime()) "][gpsd] " $0}'
