#!/usr/bin/with-contenv bash
#shellcheck shell=bash disable=SC2016

#
#ENVIRONMENT
#     See OPTION PRESETS for configuration environment variables.
#
#FILES
#     /etc/ntp.conf   the default name of the configuration file
#     /etc/ntp.drift  the default name of the drift file
#     /etc/ntp.keys   the default name of the key file
#
/usr/sbin/ntpd \
--conffile /etc/ntp.conf \
--driftfile /var/lib/ntp/ntp.drift \
-n 2>&1 | \
    stdbuf -oL awk '{print "[" strftime("%Y/%m/%d %H:%M:%S", systime()) "][ntpd] " $0}'

    