#!/usr/bin/with-contenv bash
#shellcheck shell=bash disable=SC2016

# CHECK PATH
# FIX SYNTAX TO SPECIFY CONF FILES!
/usr/bin/ntpd 2>&1 | \
    stdbuf -oL awk '{print "[" strftime("%Y/%m/%d %H:%M:%S", systime()) "][ntpd] " $0}'

    